/**
 * Suggestions de metiers (job_title) pour autocomplete.
 *
 * Cette liste sert UNIQUEMENT de suggestions dans l'input testeur (datalist
 * HTML5). Le testeur peut toujours taper sa propre valeur si elle n'est pas
 * dans la liste — la colonne testers.job_title reste TEXT libre. L'objectif
 * est de normaliser ~80% des saisies pour que les agregats restent propres
 * a 5000+ testeurs.
 *
 * Sources :
 *  - ROME (Pole Emploi, libre) : metiers classiques et secteurs etablis
 *  - INSEE PCS-2020 niveau 4 : libelles fiscaux courants
 *  - Custom earlypanel : metiers tech/digital/produit/data modernes (anglicismes)
 *
 * Maintenance : ajoute des metiers ici quand tu vois des patterns repetes en
 * "Autre" lors de tes premieres invitations. Pas besoin de courir apres
 * l'exhaustivite — 400 lignes couvrent ~95% du panel B2B francais.
 */

export const SUGGESTED_JOB_TITLES: readonly string[] = [
  // === COMPTABILITE / FINANCE / AUDIT ===
  "Comptable",
  "Comptable senior",
  "Aide-comptable",
  "Expert-comptable",
  "Expert-comptable stagiaire",
  "Auditeur financier",
  "Auditeur interne",
  "Commissaire aux comptes",
  "Contrôleur de gestion",
  "Contrôleur financier",
  "Analyste financier",
  "Trésorier",
  "Crédit manager",
  "Responsable comptable",
  "Responsable consolidation",
  "Responsable financier",
  "DAF",
  "Directeur administratif et financier",
  "Chargé de recouvrement",
  "Chargé de paie",
  "Gestionnaire de paie",
  "Responsable paie",
  "Fiscaliste",

  // === BANQUE / ASSURANCE ===
  "Conseiller bancaire",
  "Conseiller clientèle bancaire",
  "Conseiller patrimonial",
  "Gestionnaire de patrimoine",
  "Banquier privé",
  "Trader",
  "Analyste credit",
  "Analyste risques",
  "Conseiller en assurance",
  "Courtier en assurance",
  "Souscripteur",
  "Actuaire",
  "Gestionnaire de sinistres",
  "Inspecteur d'assurance",

  // === TECH / DEV / IT ===
  "Développeur",
  "Développeur web",
  "Développeur full-stack",
  "Développeur front-end",
  "Développeur back-end",
  "Développeur mobile",
  "Développeur iOS",
  "Développeur Android",
  "Développeur React",
  "Développeur Node.js",
  "Développeur Python",
  "Développeur Java",
  "Développeur PHP",
  "Développeur .NET",
  "Développeur Ruby",
  "Développeur Go",
  "Développeur Rust",
  "Développeur embarqué",
  "Développeur de jeux vidéo",
  "Lead developer",
  "Tech lead",
  "Architecte logiciel",
  "Architecte SI",
  "Architecte cloud",
  "Architecte sécurité",
  "Ingénieur logiciel",
  "Ingénieur DevOps",
  "Ingénieur SRE",
  "Ingénieur cloud",
  "Ingénieur cybersécurité",
  "Ingénieur réseau",
  "Ingénieur systèmes",
  "Ingénieur QA",
  "Ingénieur test",
  "Ingénieur d'études",
  "Ingénieur R&D",
  "Administrateur systèmes",
  "Administrateur réseau",
  "Administrateur base de données",
  "Technicien support",
  "Technicien helpdesk",
  "Technicien infrastructure",
  "Responsable infrastructure",
  "Responsable IT",
  "DSI",
  "Directeur des systèmes d'information",
  "CTO",
  "VP Engineering",
  "Engineering Manager",
  "Scrum master",
  "Product owner",
  "Coach Agile",
  "Chef de projet IT",
  "Chef de projet digital",
  "Chef de projet web",
  "Consultant IT",
  "Consultant cybersécurité",
  "Pentester",
  "RSSI",
  "Directeur sécurité informatique",

  // === DATA / IA ===
  "Data analyst",
  "Data scientist",
  "Data engineer",
  "Machine learning engineer",
  "Ingénieur IA",
  "Chief Data Officer",
  "Lead data",
  "Analyste BI",
  "Business Intelligence Manager",

  // === PRODUIT / DESIGN ===
  "Product manager",
  "Senior product manager",
  "Lead product manager",
  "Group product manager",
  "Head of Product",
  "Chief Product Officer",
  "Product designer",
  "UX designer",
  "UI designer",
  "UX researcher",
  "Lead designer",
  "Head of Design",
  "Design Ops",
  "Product marketing manager",
  "Product Ops",
  "Growth product manager",

  // === MARKETING / COMMUNICATION / GROWTH ===
  "Chef de produit marketing",
  "Responsable marketing",
  "Directeur marketing",
  "CMO",
  "Marketing manager",
  "Brand manager",
  "Trafic manager",
  "SEO manager",
  "Consultant SEO",
  "Consultant SEA",
  "Growth hacker",
  "Growth manager",
  "Acquisition manager",
  "CRM manager",
  "Email marketing manager",
  "Content manager",
  "Social media manager",
  "Community manager",
  "Responsable communication",
  "Chargé de communication",
  "Attaché de presse",
  "Directeur de la communication",
  "Rédacteur web",
  "Copywriter",
  "Concepteur-rédacteur",
  "Journaliste",
  "Influenceur",
  "Directeur artistique",
  "Graphiste",
  "Motion designer",
  "Photographe",
  "Vidéaste",

  // === RH ===
  "Chargé de recrutement",
  "Recruteur",
  "Talent acquisition manager",
  "Chasseur de têtes",
  "Responsable RH",
  "Directeur des ressources humaines",
  "DRH",
  "HR Business Partner",
  "Gestionnaire administration du personnel",
  "Responsable formation",
  "Office manager",
  "Happiness manager",
  "Consultant RH",

  // === COMMERCE / VENTE / BUSINESS ===
  "Commercial",
  "Commercial sédentaire",
  "Commercial terrain",
  "Business developer",
  "Sales executive",
  "Sales manager",
  "Sales director",
  "Account executive",
  "Account manager",
  "Key account manager",
  "Customer success manager",
  "Customer support manager",
  "SDR",
  "BDR",
  "Inside sales",
  "Responsable des ventes",
  "Directeur commercial",
  "Chief Revenue Officer",
  "Téléconseiller",
  "Vendeur",
  "Représentant",
  "VRP",
  "Chargé d'affaires",

  // === DIRECTION / MANAGEMENT ===
  "CEO",
  "Président",
  "Directeur général",
  "Directeur général adjoint",
  "Cofondateur",
  "Fondateur",
  "Entrepreneur",
  "Directeur de division",
  "Directeur de site",
  "Directeur d'agence",
  "Chief of Staff",
  "COO",
  "Chief Operating Officer",
  "Directeur des opérations",
  "Directeur de filiale",
  "Manager",
  "Team lead",
  "Responsable d'équipe",

  // === CONSEIL / STRATEGIE ===
  "Consultant",
  "Consultant junior",
  "Consultant senior",
  "Manager (cabinet de conseil)",
  "Senior manager (cabinet)",
  "Associé",
  "Partner",
  "Strategy consultant",
  "Consultant en management",
  "Consultant en transformation",
  "Consultant en organisation",
  "Auditeur conseil",

  // === JURIDIQUE ===
  "Avocat",
  "Avocat collaborateur",
  "Avocat associé",
  "Juriste",
  "Juriste d'entreprise",
  "Responsable juridique",
  "Directeur juridique",
  "Notaire",
  "Notaire stagiaire",
  "Huissier de justice",
  "Mandataire judiciaire",
  "Greffier",
  "Magistrat",
  "Compliance officer",
  "DPO",
  "Délégué à la protection des données",

  // === SANTE / MEDICAL ===
  "Médecin",
  "Médecin généraliste",
  "Médecin spécialiste",
  "Chirurgien",
  "Anesthésiste",
  "Pédiatre",
  "Cardiologue",
  "Dermatologue",
  "Psychiatre",
  "Radiologue",
  "Interne en médecine",
  "Externe en médecine",
  "Infirmier",
  "Infirmier libéral",
  "Aide-soignant",
  "Auxiliaire de puériculture",
  "Sage-femme",
  "Kinésithérapeute",
  "Ostéopathe",
  "Psychologue",
  "Psychomotricien",
  "Orthophoniste",
  "Ergothérapeute",
  "Diététicien",
  "Nutritionniste",
  "Pharmacien",
  "Préparateur en pharmacie",
  "Dentiste",
  "Chirurgien-dentiste",
  "Orthodontiste",
  "Vétérinaire",
  "Opticien",
  "Audioprothésiste",
  "Manipulateur radio",
  "Assistant de vie",
  "Aide à domicile",

  // === EDUCATION / RECHERCHE ===
  "Professeur des écoles",
  "Instituteur",
  "Professeur de collège",
  "Professeur de lycée",
  "Professeur agrégé",
  "Professeur certifié",
  "Professeur d'université",
  "Maître de conférences",
  "Doctorant",
  "Post-doctorant",
  "Chercheur",
  "Chercheur en biologie",
  "Chercheur en physique",
  "Chercheur en chimie",
  "Ingénieur de recherche",
  "Animateur",
  "Éducateur spécialisé",
  "Conseiller principal d'éducation",
  "Documentaliste",
  "Bibliothécaire",
  "Directeur d'école",
  "Proviseur",
  "Formateur",
  "Coach professionnel",

  // === INDUSTRIE / PRODUCTION ===
  "Ingénieur production",
  "Ingénieur méthodes",
  "Ingénieur qualité",
  "Ingénieur industrialisation",
  "Ingénieur procédés",
  "Ingénieur maintenance",
  "Technicien de maintenance",
  "Technicien méthodes",
  "Technicien qualité",
  "Responsable production",
  "Responsable qualité",
  "Responsable maintenance",
  "Directeur d'usine",
  "Chef d'atelier",
  "Chef d'équipe production",
  "Opérateur de production",
  "Conducteur de ligne",
  "Régleur",
  "Soudeur",
  "Tourneur-fraiseur",
  "Dessinateur industriel",
  "Bureau d'études",
  "Chef de projet industriel",

  // === BTP / CONSTRUCTION / ARCHITECTURE ===
  "Architecte",
  "Architecte d'intérieur",
  "Maître d'oeuvre",
  "Conducteur de travaux",
  "Chef de chantier",
  "Ingénieur travaux",
  "Ingénieur structure",
  "Ingénieur génie civil",
  "Économiste de la construction",
  "Géomètre",
  "Géomètre-topographe",
  "Métreur",
  "Chargé d'études BTP",
  "Maçon",
  "Charpentier",
  "Plombier",
  "Électricien",
  "Peintre en bâtiment",
  "Couvreur",
  "Carreleur",
  "Menuisier",
  "Promoteur immobilier",

  // === IMMOBILIER ===
  "Agent immobilier",
  "Négociateur immobilier",
  "Conseiller immobilier",
  "Gestionnaire de copropriété",
  "Syndic",
  "Administrateur de biens",
  "Property manager",
  "Asset manager",
  "Expert immobilier",

  // === HOTELLERIE / RESTAURATION / TOURISME ===
  "Chef de cuisine",
  "Chef étoilé",
  "Cuisinier",
  "Commis de cuisine",
  "Pâtissier",
  "Boulanger",
  "Sommelier",
  "Maître d'hôtel",
  "Serveur",
  "Barman",
  "Réceptionniste",
  "Gouvernante",
  "Directeur d'hôtel",
  "Restaurateur",
  "Agent de voyages",
  "Guide touristique",
  "Animateur tourisme",

  // === TRANSPORT / LOGISTIQUE ===
  "Chauffeur poids lourd",
  "Chauffeur livreur",
  "Chauffeur VTC",
  "Taxi",
  "Pilote de ligne",
  "Hôtesse de l'air / Steward",
  "Cheminot",
  "Conducteur de train",
  "Conducteur de bus",
  "Capitaine",
  "Marin",
  "Pilote de drone",
  "Responsable logistique",
  "Supply chain manager",
  "Acheteur",
  "Acheteur industriel",
  "Approvisionneur",
  "Cariste",
  "Préparateur de commandes",
  "Magasinier",
  "Manutentionnaire",
  "Affréteur",

  // === COMMERCE / RETAIL / E-COMMERCE ===
  "Vendeur en magasin",
  "Caissier",
  "Responsable de magasin",
  "Directeur de magasin",
  "Responsable e-commerce",
  "Category manager",
  "Acheteur retail",
  "Visual merchandiser",
  "Chef de rayon",

  // === AGRICULTURE / AGROALIMENTAIRE ===
  "Agriculteur",
  "Maraîcher",
  "Viticulteur",
  "Éleveur",
  "Apiculteur",
  "Horticulteur",
  "Paysagiste",
  "Jardinier",
  "Forestier",
  "Pêcheur",
  "Ouvrier agricole",
  "Technicien agricole",
  "Ingénieur agronome",
  "Œnologue",

  // === FONCTION PUBLIQUE / DEFENSE / ADMINISTRATION ===
  "Fonctionnaire",
  "Agent administratif",
  "Secrétaire administratif",
  "Attaché territorial",
  "Cadre territorial",
  "Inspecteur des finances publiques",
  "Contrôleur des impôts",
  "Douanier",
  "Policier",
  "Gendarme",
  "Pompier",
  "Militaire",
  "Officier",
  "Diplomate",
  "Ambassadeur",
  "Agent d'accueil",
  "Travailleur social",
  "Assistant social",

  // === ASSOCIATIF / ONG / IMPACT ===
  "Chargé de mission",
  "Coordinateur ONG",
  "Responsable mécénat",
  "Fundraiser",
  "Travailleur humanitaire",
  "Responsable RSE",
  "Consultant impact",

  // === MEDIAS / CULTURE / SPECTACLE ===
  "Producteur",
  "Réalisateur",
  "Scénariste",
  "Comédien",
  "Acteur",
  "Musicien",
  "Compositeur",
  "Ingénieur du son",
  "Monteur vidéo",
  "Cadreur",
  "Régisseur",
  "Rédacteur en chef",
  "Éditeur",
  "Libraire",

  // === ARTISANAT / SERVICES ===
  "Artisan",
  "Coiffeur",
  "Esthéticien",
  "Tatoueur",
  "Couturier",
  "Tailleur",
  "Cordonnier",
  "Bijoutier",
  "Horloger",
  "Fleuriste",

  // === SECRETARIAT / ADMINISTRATIF ===
  "Assistant de direction",
  "Assistant administratif",
  "Assistant commercial",
  "Secrétaire",
  "Secrétaire médicale",
  "Standardiste",
  "Hôte d'accueil",

  // === STATUT / SITUATION ===
  "Étudiant",
  "Étudiant en école de commerce",
  "Étudiant en école d'ingénieur",
  "Étudiant en droit",
  "Étudiant en médecine",
  "Étudiant en sciences",
  "Doctorant",
  "Apprenti",
  "Stagiaire",
  "Alternant",
  "Freelance",
  "Auto-entrepreneur",
  "Indépendant",
  "Consultant indépendant",
  "Retraité",
  "Demandeur d'emploi",
  "En reconversion",
  "Sans activité",
];

/** Helper : la valeur tapee est-elle dans la liste exacte ? (pour analytics futurs) */
export function isSuggestedJobTitle(value: string | null | undefined): boolean {
  if (!value) return false;
  const v = value.trim();
  return SUGGESTED_JOB_TITLES.some((j) => j.toLowerCase() === v.toLowerCase());
}
